#!/bin/sh

rm -rf work
mkdir work
fontforge -lang=ff -c 'Open("Jena1330.sfdir"); Reencode("AdobeStandardEncoding"); Generate("work/Jena1330.pfb", "", 0x410201)'
# See font forge scripting language description on
# http://fontforge.sourceforge.net/scripting-alpha.html
#   Build pfb, in addition:
#     Generate an afm file
#     Generate a 'TeX' table containing font metrics information
#     Generate a tfm file
#     Add composite (mark to base) information to the afm file

tftopl work/Jena1330.tfm work/Jena1330.pl

cp jena.tex work/jena.tex
cp II3 work/II3

cd work
pdflatex jena.tex
